CREATE TABLE IF NOT EXISTS finance_package_coststab (
  package_type INT NOT NULL,
  product_cost DECIMAL(12,2) NOT NULL DEFAULT 0,
  sales_match_ceiling DECIMAL(12,2) NOT NULL DEFAULT 0,
  admin_extra_cost DECIMAL(12,2) NOT NULL DEFAULT 0,
  notes VARCHAR(255) DEFAULT NULL,
  updated_by VARCHAR(120) DEFAULT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (package_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
