/**
 * XLSX export helpers — real .xlsx workbooks with fixed column widths so data
 * never overlaps / shows "########" the way a raw CSV does in Excel.
 *
 * Keep column widths generous enough for the widest expected value (dates need
 * ~18, full names ~26). Header row is bold + frozen.
 */
const ExcelJS = require('exceljs');

// Columns for an activation-code export. `key` matches the row objects built by
// buildCodeRows() below. Widths are in Excel "character" units.
const CODE_COLUMNS = [
  { header: '#', key: 'idx', width: 6 },
  { header: 'Code ID', key: 'codeId', width: 12 },
  { header: 'Activation Code', key: 'code', width: 22 },
  { header: 'Package', key: 'pkg', width: 24 },
  { header: 'Status', key: 'status', width: 14 },
  { header: 'Holder Username', key: 'holderUsername', width: 20 },
  { header: 'Holder Name', key: 'holderName', width: 28 },
  { header: 'Generated By', key: 'generatedBy', width: 18 },
  { header: 'Date Generated', key: 'dategen', width: 20 },
];
// Optional relationship columns (script export): how the code ties to the
// member, and — for a code they transferred — whom they handed it to (this
// reconciles the row 1:1 with the member's Code History screen).
const RELATION_COLUMN = { header: 'Relation', key: 'relation', width: 16 };
const SENT_TO_COLUMN = { header: 'Member Sent To', key: 'sentTo', width: 18 };
// Date of the code's latest usage event (transfer/registration/repurchase) —
// distinct from Date Generated, which is when the admin created the code.
const LAST_ACTIVITY_COLUMN = { header: 'Last Activity', key: 'lastActivity', width: 20 };

function applyHeaderStyle(ws, colCount) {
  const header = ws.getRow(1);
  header.font = { bold: true };
  header.alignment = { vertical: 'middle' };
  ws.views = [{ state: 'frozen', ySplit: 1 }];
  ws.autoFilter = { from: 'A1', to: `${String.fromCharCode(64 + colCount)}1` };
}

/**
 * Build an ExcelJS workbook of activation-code rows with fixed column widths.
 * @param {Array<Object>} rows objects keyed to the column keys
 * @param {{ sheetName?: string, withRelation?: boolean }} [opts]
 * @returns {ExcelJS.Workbook}
 */
function buildCodesWorkbook(rows = [], opts = {}) {
  const wb = new ExcelJS.Workbook();
  wb.creator = 'NOGATU Alliance Admin';
  wb.created = new Date();
  const ws = wb.addWorksheet(opts.sheetName || 'Activation Codes');
  // Relation + Member Sent To sit right after the row number; Last Activity
  // goes at the end after Date Generated.
  const columns = opts.withRelation
    ? [CODE_COLUMNS[0], RELATION_COLUMN, SENT_TO_COLUMN, ...CODE_COLUMNS.slice(1), LAST_ACTIVITY_COLUMN]
    : CODE_COLUMNS;
  ws.columns = columns;
  rows.forEach((r) => ws.addRow(r));
  applyHeaderStyle(ws, columns.length);
  return wb;
}

module.exports = { buildCodesWorkbook, CODE_COLUMNS };
