/**
 * READ-ONLY export — all activation codes generated for / held by a member,
 * written to a CSV that opens directly in Excel.
 *
 * "Codes generated for <member>" = codes whose current holder is that member
 * (codestab.uid) OR codes generated by that account (codestab.processid). Each
 * row is tagged with the relationship. This script performs NO writes.
 *
 * Usage (BLUE / production — where the live codes are):
 *   cd /var/www/nogatu
 *   NODE_ENV=production node scripts/export_codes_for_member.js --username tabsqui
 *   NODE_ENV=production node scripts/export_codes_for_member.js --username tabsqui --out /root/tabsqui_codes.xlsx
 *   # optional date-generated window (Manila, inclusive):
 *   NODE_ENV=production node scripts/export_codes_for_member.js --username tabsqui --from 2026-01-01 --to 2026-07-15
 *
 * Writes a real .xlsx (fixed column widths — no overlap / "########").
 */
const path = require('path');
const mysql = require('mysql2/promise');
const { loadBackendEnv, getDbConfig } = require('./env');
const { buildCodesWorkbook } = require('../services/xlsxExport');
// Authoritative package + maintenance-product names (10-60 packages,
// 100-109 repurchase products) so product codes read e.g. "Vitamin C with
// Zinc & Mangosteen", never "Type 106".
const { PRODUCT_TYPES } = require('../utils/helpers');

const STATUS = { 0: 'Not Released', 1: 'Released', 2: 'Used' };

async function tableExists(conn, name) {
  const [rows] = await conn.query('SHOW TABLES LIKE ?', [name]);
  return rows.length > 0;
}

function parseArgs(argv) {
  const out = { username: null, out: null, from: null, to: null };
  for (let i = 0; i < argv.length; i += 1) {
    const a = argv[i];
    if ((a === '--username' || a === '-u') && argv[i + 1]) { out.username = argv[++i]; }
    else if (a === '--out' && argv[i + 1]) { out.out = argv[++i]; }
    else if (a === '--from' && argv[i + 1]) { out.from = argv[++i]; }
    else if (a === '--to' && argv[i + 1]) { out.to = argv[++i]; }
    else if (a === '--help' || a === '-h') { out.help = true; }
  }
  return out;
}

async function main() {
  const opts = parseArgs(process.argv.slice(2));
  if (opts.help || !opts.username) {
    console.log('Usage: NODE_ENV=production node scripts/export_codes_for_member.js --username <name> [--out file.xlsx] [--from YYYY-MM-DD] [--to YYYY-MM-DD]');
    return;
  }

  const envFile = loadBackendEnv();
  const dbConfig = getDbConfig();
  console.log(`env=${process.env.NODE_ENV || 'unset'} (${envFile}) DB=${dbConfig.user}@${dbConfig.host}/${dbConfig.database}`);

  const username = String(opts.username).trim();
  const conn = await mysql.createConnection(dbConfig);
  try {
    const [memberRows] = await conn.query(
      'SELECT uid, username, TRIM(CONCAT(COALESCE(firstname,\'\'),\' \',COALESCE(lastname,\'\'))) AS fullname FROM memberstab WHERE username = ? OR TRIM(username) = ?',
      [username, username]
    );
    const targetUid = memberRows.length === 1 ? memberRows[0].uid : null;
    if (memberRows.length > 1) {
      console.log(`Note: ${memberRows.length} member rows match "${username}" — using none as holder; still matching processid.`);
    } else if (memberRows.length === 1) {
      console.log(`Member: uid=${targetUid} username="${memberRows[0].username}" name="${memberRows[0].fullname}"`);
    } else {
      console.log(`Note: "${username}" not found in memberstab — matching processid (generator) only.`);
    }

    // Per-code relationship flags from the SAME event source the member's Code
    // History screen reads (activation_code_usagetab), so the export includes
    // codes she transferred out or used — not just what she currently holds.
    let flagsByCode = new Map();
    const sentToByCode = new Map();
    const lastActivityByCode = new Map();
    if (targetUid != null && await tableExists(conn, 'activation_code_usagetab')) {
      const [flagRows] = await conn.query(
        `SELECT code,
                MAX(registration_uid = ? OR upgrade_uid = ?) AS used_by_her,
                MAX(from_uid = ? OR actor_uid = ?) AS moved_by_her,
                MAX(to_uid = ?) AS received_by_her
         FROM activation_code_usagetab
         WHERE from_uid = ? OR to_uid = ? OR actor_uid = ? OR registration_uid = ? OR upgrade_uid = ?
         GROUP BY code`,
        [targetUid, targetUid, targetUid, targetUid, targetUid,
         targetUid, targetUid, targetUid, targetUid, targetUid]
      );
      flagsByCode = new Map(flagRows.map((f) => [f.code, f]));

      // Latest recipient this member transferred each code to (matches the
      // "tabsqui transferred this code to X" lines in her Code History).
      const [sentRows] = await conn.query(
        `SELECT a.code, tm.username AS sent_to
         FROM activation_code_usagetab a
         LEFT JOIN memberstab tm ON tm.uid = a.to_uid
         WHERE (a.from_uid = ? OR a.actor_uid = ?) AND a.to_uid IS NOT NULL AND a.to_uid <> ?
         ORDER BY a.id DESC`,
        [targetUid, targetUid, targetUid]
      );
      for (const s of sentRows) {
        if (s.code && !sentToByCode.has(s.code)) sentToByCode.set(s.code, s.sent_to || `UID ${s.code}`);
      }

      // Latest event date per code (any event, any party) — "Last Activity".
      // Date Generated alone misleads: a code generated in June can have July
      // transfers; this column carries the July date the history screen shows.
      const [lastRows] = await conn.query(
        `SELECT code, DATE_FORMAT(MAX(created_at),'%Y-%m-%d %H:%i') last_at
         FROM activation_code_usagetab
         WHERE from_uid = ? OR to_uid = ? OR actor_uid = ? OR registration_uid = ? OR upgrade_uid = ?
         GROUP BY code`,
        [targetUid, targetUid, targetUid, targetUid, targetUid]
      );
      for (const l of lastRows) lastActivityByCode.set(l.code, l.last_at);
    }

    // Complete code set: currently held (c.uid) OR generated by her (processid)
    // OR any code that appears in her usage-event history.
    const params = [];
    const orParts = [];
    if (targetUid != null) { orParts.push('c.uid = ?'); params.push(targetUid); }
    orParts.push('c.processid = ?'); params.push(username);
    if (targetUid != null) {
      orParts.push(`c.code IN (
        SELECT code FROM activation_code_usagetab
        WHERE from_uid = ? OR to_uid = ? OR actor_uid = ? OR registration_uid = ? OR upgrade_uid = ?
      )`);
      params.push(targetUid, targetUid, targetUid, targetUid, targetUid);
    }
    let dateSql = '';
    if (opts.from) { dateSql += ' AND c.dategen >= ?'; params.push(`${opts.from} 00:00:00`); }
    if (opts.to)   { dateSql += ' AND c.dategen < DATE_ADD(?, INTERVAL 1 DAY)'; params.push(opts.to); }

    const [rows] = await conn.query(
      `SELECT c.id, c.code, c.producttype, c.codestatus, c.releasedate, c.processid, c.uid,
              DATE_FORMAT(c.dategen, '%Y-%m-%d %H:%i') AS dategen,
              m.username AS holder_username,
              TRIM(CONCAT(COALESCE(m.firstname,''),' ',COALESCE(m.lastname,''))) AS holder_name
       FROM codestab c
       LEFT JOIN memberstab m ON m.uid = c.uid
       WHERE (${orParts.join(' OR ')})${dateSql}
       ORDER BY c.dategen DESC, c.id DESC`,
      params
    );

    if (rows.length === 0) {
      console.log('No codes found for that member/window. Nothing written.');
      return;
    }

    // Relation reflects the code's current custody vs this member:
    //   held           = she holds it now (c.uid = her)
    //   used           = she used/registered it (no longer just held)
    //   transferred_out= she moved it to someone else; another account holds it
    //   received       = it was transferred TO her but she doesn't hold it now
    //   generated_by   = her account generated it (processid) with no other tie
    const relationCounts = {};
    const byStatus = { 0: 0, 1: 0, 2: 0 };
    const xlsxRows = rows.map((r, i) => {
      byStatus[r.codestatus] = (byStatus[r.codestatus] || 0) + 1;
      const f = flagsByCode.get(r.code);
      const held = targetUid != null && r.uid === targetUid;
      let relation;
      // "used" wins over "held": a code she consumed for her own repurchase/
      // upgrade stays in her name (uid unchanged) but reads better as used.
      // Codes she merely holds that a downline registered with are NOT
      // used_by_her (registration_uid is the downline), so they stay "held".
      if (f && Number(f.used_by_her)) relation = 'used';
      else if (held) relation = (r.processid === username ? 'held+generated' : 'held');
      else if (f && Number(f.moved_by_her)) relation = 'transferred_out';
      else if (f && Number(f.received_by_her)) relation = 'received';
      else if (r.processid === username) relation = 'generated_by';
      else relation = 'associated';
      relationCounts[relation] = (relationCounts[relation] || 0) + 1;
      return {
        idx: i + 1,
        relation,
        sentTo: sentToByCode.get(r.code) || '',
        codeId: r.id,
        code: r.code,
        pkg: PRODUCT_TYPES[r.producttype] || `Type ${r.producttype}`,
        status: STATUS[r.codestatus] || r.codestatus,
        holderUsername: r.holder_username || '',
        holderName: r.holder_name || '',
        generatedBy: r.processid || '',
        dategen: r.dategen || '',
        lastActivity: lastActivityByCode.get(r.code) || '',
      };
    });

    const wb = buildCodesWorkbook(xlsxRows, { sheetName: `codes_${username}`.slice(0, 31), withRelation: true });
    const stamp = new Date().toISOString().slice(0, 10);
    const outPath = opts.out || path.resolve(process.cwd(), `codes_${username}_${stamp}.xlsx`);
    await wb.xlsx.writeFile(outPath);

    console.log('-------------------------------------------------------------');
    console.log(`Rows: ${rows.length}  (Not Released ${byStatus[0]||0} | Released ${byStatus[1]||0} | Used ${byStatus[2]||0})`);
    console.log(`By relation: ${Object.entries(relationCounts).map(([k, v]) => `${k} ${v}`).join(' | ')}`);
    console.log(`Written: ${outPath}`);
  } finally {
    await conn.end();
  }
}

main().catch((err) => {
  console.error('[export_codes_for_member] FATAL:', err.message);
  process.exitCode = 1;
});
