/**
 * READ-ONLY export — all activation codes generated for / held by a member,
 * written to a CSV that opens directly in Excel.
 *
 * "Codes generated for <member>" = codes whose current holder is that member
 * (codestab.uid) OR codes generated by that account (codestab.processid). Each
 * row is tagged with the relationship. This script performs NO writes.
 *
 * Usage (BLUE / production — where the live codes are):
 *   cd /var/www/nogatu
 *   NODE_ENV=production node scripts/export_codes_for_member.js --username tabsqui
 *   NODE_ENV=production node scripts/export_codes_for_member.js --username tabsqui --out /root/tabsqui_codes.xlsx
 *   # optional date-generated window (Manila, inclusive):
 *   NODE_ENV=production node scripts/export_codes_for_member.js --username tabsqui --from 2026-01-01 --to 2026-07-15
 *
 * Writes a real .xlsx (fixed column widths — no overlap / "########").
 */
const path = require('path');
const mysql = require('mysql2/promise');
const { loadBackendEnv, getDbConfig } = require('./env');
const { buildCodesWorkbook } = require('../services/xlsxExport');

// Package/product-type names (mirror of utils/helpers PRODUCT_TYPES for the
// entry packages; anything else falls back to "Type <n>").
const PRODUCT_NAMES = {
  10: 'Bronze', 20: 'Silver', 30: 'Gold', 40: 'Platinum', 50: 'Garnet', 60: 'Diamond',
};
const STATUS = { 0: 'Not Released', 1: 'Released', 2: 'Used' };

function parseArgs(argv) {
  const out = { username: null, out: null, from: null, to: null };
  for (let i = 0; i < argv.length; i += 1) {
    const a = argv[i];
    if ((a === '--username' || a === '-u') && argv[i + 1]) { out.username = argv[++i]; }
    else if (a === '--out' && argv[i + 1]) { out.out = argv[++i]; }
    else if (a === '--from' && argv[i + 1]) { out.from = argv[++i]; }
    else if (a === '--to' && argv[i + 1]) { out.to = argv[++i]; }
    else if (a === '--help' || a === '-h') { out.help = true; }
  }
  return out;
}

async function main() {
  const opts = parseArgs(process.argv.slice(2));
  if (opts.help || !opts.username) {
    console.log('Usage: NODE_ENV=production node scripts/export_codes_for_member.js --username <name> [--out file.xlsx] [--from YYYY-MM-DD] [--to YYYY-MM-DD]');
    return;
  }

  const envFile = loadBackendEnv();
  const dbConfig = getDbConfig();
  console.log(`env=${process.env.NODE_ENV || 'unset'} (${envFile}) DB=${dbConfig.user}@${dbConfig.host}/${dbConfig.database}`);

  const username = String(opts.username).trim();
  const conn = await mysql.createConnection(dbConfig);
  try {
    const [memberRows] = await conn.query(
      'SELECT uid, username, TRIM(CONCAT(COALESCE(firstname,\'\'),\' \',COALESCE(lastname,\'\'))) AS fullname FROM memberstab WHERE username = ? OR TRIM(username) = ?',
      [username, username]
    );
    const targetUid = memberRows.length === 1 ? memberRows[0].uid : null;
    if (memberRows.length > 1) {
      console.log(`Note: ${memberRows.length} member rows match "${username}" — using none as holder; still matching processid.`);
    } else if (memberRows.length === 1) {
      console.log(`Member: uid=${targetUid} username="${memberRows[0].username}" name="${memberRows[0].fullname}"`);
    } else {
      console.log(`Note: "${username}" not found in memberstab — matching processid (generator) only.`);
    }

    const params = [];
    let where = '(';
    if (targetUid != null) { where += 'c.uid = ? OR '; params.push(targetUid); }
    where += 'c.processid = ?)';
    params.push(username);

    let dateSql = '';
    if (opts.from) { dateSql += ' AND c.dategen >= ?'; params.push(`${opts.from} 00:00:00`); }
    if (opts.to)   { dateSql += ' AND c.dategen < DATE_ADD(?, INTERVAL 1 DAY)'; params.push(opts.to); }

    const [rows] = await conn.query(
      `SELECT c.id, c.code, c.producttype, c.codestatus, c.releasedate, c.processid, c.uid,
              DATE_FORMAT(c.dategen, '%Y-%m-%d %H:%i') AS dategen,
              m.username AS holder_username,
              TRIM(CONCAT(COALESCE(m.firstname,''),' ',COALESCE(m.lastname,''))) AS holder_name
       FROM codestab c
       LEFT JOIN memberstab m ON m.uid = c.uid
       WHERE ${where}${dateSql}
       ORDER BY c.dategen DESC, c.id DESC`,
      params
    );

    if (rows.length === 0) {
      console.log('No codes found for that member/window. Nothing written.');
      return;
    }

    const byStatus = { 0: 0, 1: 0, 2: 0 };
    const xlsxRows = rows.map((r, i) => {
      byStatus[r.codestatus] = (byStatus[r.codestatus] || 0) + 1;
      const relation = (targetUid != null && r.uid === targetUid)
        ? (r.processid === username ? 'held+generated' : 'held')
        : 'generated_by';
      return {
        idx: i + 1,
        relation,
        codeId: r.id,
        code: r.code,
        pkg: PRODUCT_NAMES[r.producttype] || `Type ${r.producttype}`,
        status: STATUS[r.codestatus] || r.codestatus,
        holderUsername: r.holder_username || '',
        holderName: r.holder_name || '',
        generatedBy: r.processid || '',
        dategen: r.dategen || '',
      };
    });

    const wb = buildCodesWorkbook(xlsxRows, { sheetName: `codes_${username}`.slice(0, 31), withRelation: true });
    const stamp = new Date().toISOString().slice(0, 10);
    const outPath = opts.out || path.resolve(process.cwd(), `codes_${username}_${stamp}.xlsx`);
    await wb.xlsx.writeFile(outPath);

    console.log('-------------------------------------------------------------');
    console.log(`Rows: ${rows.length}  (Not Released ${byStatus[0]||0} | Released ${byStatus[1]||0} | Used ${byStatus[2]||0})`);
    console.log(`Written: ${outPath}`);
  } finally {
    await conn.end();
  }
}

main().catch((err) => {
  console.error('[export_codes_for_member] FATAL:', err.message);
  process.exitCode = 1;
});
