/**
 * READ-ONLY code lookup / trail report → .xlsx (fixed column widths).
 *
 * Answers three shapes of question:
 *   1. "Look up these Code IDs"           --ids 10657,10522,...  (or --ids-file list.txt)
 *   2. "Codes generated by X in a window" --generated-by nogatuadmin --from 2026-01-14 --to 2026-01-16
 *   3. "Codes whose trail is (X)member"   --generated-by nogatuadmin --initial-to tabsqui
 *
 * "Initially Transferred To" = the recipient of the code's FIRST transfer event
 * (admin_transfer or transfer, earliest by id) — i.e. who the code was handed to
 * first, regardless of where it moved afterwards. That is the "(nogatuadmin)tabsqui"
 * trail shown on Manage Codes.
 *
 * Performs NO writes.
 *
 * Usage (BLUE / production):
 *   cd /var/www/nogatu
 *   NODE_ENV=production node scripts/lookup_codes.js --ids 10657,10522 --out /root/lookup.xlsx
 *   NODE_ENV=production node scripts/lookup_codes.js --generated-by nogatuadmin --from 2026-01-14 --to 2026-01-16 --out /root/jan14-16.xlsx
 *   NODE_ENV=production node scripts/lookup_codes.js --generated-by nogatuadmin --initial-to tabsqui --out /root/trail.xlsx
 */
const fs = require('fs');
const path = require('path');
const mysql = require('mysql2/promise');
const ExcelJS = require('exceljs');
const { loadBackendEnv, getDbConfig } = require('./env');
const { PRODUCT_TYPES } = require('../utils/helpers');

const STATUS = { 0: 'Not Released', 1: 'Released', 2: 'Used' };
const TRANSFER_EVENTS = ['admin_transfer', 'transfer'];
const ISO_DATE = /^\d{4}-\d{2}-\d{2}$/;
const CHUNK = 500;

const COLUMNS = [
  { header: '#', key: 'idx', width: 6 },
  { header: 'Code ID', key: 'codeId', width: 12 },
  { header: 'Activation Code', key: 'code', width: 22 },
  { header: 'Package', key: 'pkg', width: 30 },
  { header: 'Status', key: 'status', width: 14 },
  { header: 'Trail', key: 'trail', width: 26 },
  { header: 'Initially Transferred To', key: 'initialTo', width: 24 },
  { header: 'Initially Transferred By', key: 'initialBy', width: 24 },
  { header: 'Holder Username', key: 'holderUsername', width: 20 },
  { header: 'Holder Name', key: 'holderName', width: 28 },
  { header: 'Generated By', key: 'generatedBy', width: 18 },
  { header: 'Date Generated', key: 'dategen', width: 20 },
  { header: 'Last Activity', key: 'lastActivity', width: 20 },
];

function parseArgs(argv) {
  const o = { ids: [], generatedBy: null, initialTo: null, from: null, to: null, out: null };
  for (let i = 0; i < argv.length; i += 1) {
    const a = argv[i];
    const next = argv[i + 1];
    if (a === '--ids' && next) { o.ids = next.split(',').map((s) => Number(s.trim())).filter(Boolean); i += 1; }
    else if (a === '--ids-file' && next) {
      o.ids = fs.readFileSync(next, 'utf8').split(/[\s,]+/).map((s) => Number(s.trim())).filter(Boolean); i += 1;
    }
    else if (a === '--generated-by' && next) { o.generatedBy = next; i += 1; }
    else if (a === '--initial-to' && next) { o.initialTo = next; i += 1; }
    else if (a === '--from' && next) { o.from = next; i += 1; }
    else if (a === '--to' && next) { o.to = next; i += 1; }
    else if (a === '--out' && next) { o.out = next; i += 1; }
    else if (a === '--help' || a === '-h') { o.help = true; }
  }
  return o;
}

function chunk(arr, size = CHUNK) {
  const out = [];
  for (let i = 0; i < arr.length; i += size) out.push(arr.slice(i, i + size));
  return out;
}

/**
 * Parse a legacy codehistorytab.history trail. Older codes predate
 * activation_code_usagetab, so this string is their ONLY trail source.
 *
 * TWO formats exist and they carry different semantics:
 *  1. Parenthesised (admin / legacy PHP): "(nogatuadmin)Ann050890 -> (Ann050890)Malou05"
 *     Each segment is self-contained "(actor)recipient"; hop 1 = segment 0.
 *  2. Plain (Node member transfer, routes/codes.js): "tabsqui->VernieS01"
 *     Segments are usernames: from -> to.
 * Returns the code's FIRST transfer (actor + recipient) plus the whole chain.
 */
function parseLegacyTrail(history) {
  if (!history) return null;
  const raw = String(history).trim();
  if (!raw) return null;
  const segments = raw.split('->').map((s) => s.trim()).filter(Boolean);
  if (segments.length === 0) return null;

  if (raw.includes('(')) {
    const seg0 = segments[0];
    return {
      actor: (seg0.match(/^\(([^)]+)\)/) || [])[1]?.trim() || null,
      recipient: (seg0.match(/\)\s*(.+)$/) || [])[1]?.trim() || null,
      full: raw,
    };
  }
  return { actor: segments[0] || null, recipient: segments[1] || null, full: raw };
}

const sameUser = (a, b) => String(a || '').trim().toLowerCase() === String(b || '').trim().toLowerCase();

async function main() {
  const opts = parseArgs(process.argv.slice(2));
  if (opts.help || (opts.ids.length === 0 && !opts.generatedBy && !opts.initialTo)) {
    console.log('Usage: NODE_ENV=production node scripts/lookup_codes.js [--ids 1,2,3 | --ids-file f.txt] [--generated-by <admin>] [--initial-to <member>] [--from YYYY-MM-DD] [--to YYYY-MM-DD] [--out file.xlsx]');
    return;
  }

  const envFile = loadBackendEnv();
  const dbConfig = getDbConfig();
  console.log(`env=${process.env.NODE_ENV || 'unset'} (${envFile}) DB=${dbConfig.user}@${dbConfig.host}/${dbConfig.database}`);

  const conn = await mysql.createConnection(dbConfig);
  try {
    // ---- optional: restrict to codes whose FIRST transfer went to --initial-to
    let initialToCodes = null;
    if (opts.initialTo) {
      const [mem] = await conn.query(
        'SELECT uid, username FROM memberstab WHERE username = ? OR TRIM(username) = ? LIMIT 1',
        [opts.initialTo, opts.initialTo]
      );
      if (mem.length === 0) {
        console.log(`Member "${opts.initialTo}" not found. Nothing written.`);
        return;
      }
      const targetUid = mem[0].uid;
      console.log(`Initial-transfer target: uid=${targetUid} username="${mem[0].username}"`);
      // Candidate codes: anything ever transferred TO them.
      const [cand] = await conn.query(
        `SELECT DISTINCT code FROM activation_code_usagetab
         WHERE to_uid = ? AND event_type IN (?, ?)`,
        [targetUid, ...TRANSFER_EVENTS]
      );
      const candCodes = cand.map((r) => r.code);
      // Keep only those whose EARLIEST transfer recipient is this member.
      const found = new Set();
      for (const part of chunk(candCodes)) {
        if (part.length === 0) continue;
        const [firsts] = await conn.query(
          `SELECT a.code, a.to_uid
           FROM activation_code_usagetab a
           INNER JOIN (
             SELECT code, MIN(id) AS first_id
             FROM activation_code_usagetab
             WHERE event_type IN (?, ?) AND code IN (${part.map(() => '?').join(',')})
             GROUP BY code
           ) f ON f.code = a.code AND f.first_id = a.id`,
          [...TRANSFER_EVENTS, ...part]
        );
        for (const f of firsts) if (Number(f.to_uid) === Number(targetUid)) found.add(f.code);
      }
      const fromEvents = found.size;

      // LEGACY: codes predating activation_code_usagetab keep their trail only in
      // codehistorytab.history — "(nogatuadmin)tabsqui -> (tabsqui)someoneelse".
      // Broad LIKE then exact first-segment parse (LIKE alone would match a member
      // appearing anywhere later in the chain).
      const [legacyCand] = await conn.query(
        'SELECT code, history FROM codehistorytab WHERE history LIKE ?',
        [`%${mem[0].username}%`]
      );
      for (const r of legacyCand) {
        const t = parseLegacyTrail(r.history);
        if (t && sameUser(t.recipient, mem[0].username)) found.add(r.code);
      }
      initialToCodes = [...found];
      console.log(`Codes whose FIRST transfer went to "${opts.initialTo}": ${initialToCodes.length} (events: ${fromEvents}, legacy trail: ${initialToCodes.length - fromEvents})`);
      if (initialToCodes.length === 0) { console.log('Nothing written.'); return; }
    }

    // ---- main filter
    const conds = [];
    const params = [];
    if (opts.ids.length > 0) { conds.push(`c.id IN (${opts.ids.map(() => '?').join(',')})`); params.push(...opts.ids); }
    if (opts.generatedBy) { conds.push('c.processid = ?'); params.push(opts.generatedBy); }
    if (ISO_DATE.test(opts.from || '')) { conds.push('c.dategen >= ?'); params.push(`${opts.from} 00:00:00`); }
    if (ISO_DATE.test(opts.to || '')) { conds.push('c.dategen < DATE_ADD(?, INTERVAL 1 DAY)'); params.push(opts.to); }
    if (initialToCodes) { conds.push(`c.code IN (${initialToCodes.map(() => '?').join(',')})`); params.push(...initialToCodes); }
    if (conds.length === 0) { console.log('No filters resolved. Nothing written.'); return; }

    const [rows] = await conn.query(
      `SELECT c.id, c.code, c.producttype, c.codestatus, c.processid,
              DATE_FORMAT(c.dategen, '%Y-%m-%d %H:%i') AS dategen,
              m.username AS holder_username,
              TRIM(CONCAT(COALESCE(m.firstname,''),' ',COALESCE(m.lastname,''))) AS holder_name
       FROM codestab c
       LEFT JOIN memberstab m ON m.uid = c.uid
       WHERE ${conds.join(' AND ')}
       ORDER BY c.dategen DESC, c.id DESC`,
      params
    );
    if (rows.length === 0) { console.log('No codes matched. Nothing written.'); return; }

    // ---- first-transfer + last-activity per code (for display)
    const codes = rows.map((r) => r.code);
    const firstByCode = new Map();
    const lastByCode = new Map();
    const legacyByCode = new Map();
    for (const part of chunk(codes)) {
      const ph = part.map(() => '?').join(',');
      const [firsts] = await conn.query(
        `SELECT a.code, a.event_type,
                tm.username AS to_username,
                am.username AS actor_member,
                aa.username AS actor_admin
         FROM activation_code_usagetab a
         INNER JOIN (
           SELECT code, MIN(id) AS first_id
           FROM activation_code_usagetab
           WHERE event_type IN (?, ?) AND code IN (${ph})
           GROUP BY code
         ) f ON f.code = a.code AND f.first_id = a.id
         LEFT JOIN memberstab tm ON tm.uid = a.to_uid
         LEFT JOIN memberstab am ON am.uid = a.actor_uid
         LEFT JOIN accesstab aa ON aa.id = a.actor_admin_id`,
        [...TRANSFER_EVENTS, ...part]
      );
      for (const f of firsts) firstByCode.set(f.code, f);

      const [lasts] = await conn.query(
        `SELECT code, DATE_FORMAT(MAX(created_at),'%Y-%m-%d %H:%i') AS last_at
         FROM activation_code_usagetab WHERE code IN (${ph}) GROUP BY code`,
        part
      );
      for (const l of lasts) lastByCode.set(l.code, l.last_at);

      // Legacy trail + transfer date for codes with no usage events.
      const [legacy] = await conn.query(
        `SELECT code, history, DATE_FORMAT(datetransfer,'%Y-%m-%d %H:%i') AS datetransfer
         FROM codehistorytab WHERE code IN (${ph})
         ORDER BY datetransfer DESC, id DESC`,
        part
      );
      for (const l of legacy) {
        if (!legacyByCode.has(l.code)) legacyByCode.set(l.code, l);
      }
    }

    let legacyUsed = 0;
    let noTrail = 0;
    const xrows = rows.map((r, i) => {
      const f = firstByCode.get(r.code);
      const lg = parseLegacyTrail(legacyByCode.get(r.code)?.history);
      // Node-era events win; fall back to the legacy trail string for older codes.
      let initialBy = f ? (f.actor_admin || f.actor_member || '') : '';
      let initialTo = f ? (f.to_username || '') : '';
      let trail = initialBy && initialTo ? `(${initialBy})${initialTo}` : '';
      if (!initialTo && lg) {
        initialBy = lg.actor || '';
        initialTo = lg.recipient || '';
        trail = lg.full;
        legacyUsed += 1;
      } else if (lg && lg.full) {
        trail = lg.full; // legacy string carries the whole chain, not just hop 1
      }
      if (!initialTo) noTrail += 1;
      return {
        idx: i + 1,
        codeId: r.id,
        code: r.code,
        pkg: PRODUCT_TYPES[r.producttype] || `Type ${r.producttype}`,
        status: STATUS[r.codestatus] || r.codestatus,
        trail,
        initialTo,
        initialBy,
        holderUsername: r.holder_username || '',
        holderName: r.holder_name || '',
        generatedBy: r.processid || '',
        dategen: r.dategen || '',
        lastActivity: lastByCode.get(r.code) || legacyByCode.get(r.code)?.datetransfer || '',
      };
    });

    const wb = new ExcelJS.Workbook();
    wb.creator = 'NOGATU Alliance Admin';
    wb.created = new Date();
    const ws = wb.addWorksheet('Code Lookup');
    ws.columns = COLUMNS;
    xrows.forEach((r) => ws.addRow(r));
    ws.getRow(1).font = { bold: true };
    ws.views = [{ state: 'frozen', ySplit: 1 }];
    ws.autoFilter = { from: 'A1', to: `${String.fromCharCode(64 + COLUMNS.length)}1` };

    const stamp = new Date().toISOString().slice(0, 10);
    const outPath = opts.out || path.resolve(process.cwd(), `code_lookup_${stamp}.xlsx`);
    await wb.xlsx.writeFile(outPath);

    console.log('-------------------------------------------------------------');
    console.log(`Matched: ${rows.length}`);
    console.log(`Trail source: events ${rows.length - legacyUsed - noTrail} | legacy codehistorytab ${legacyUsed} | NO TRAIL FOUND ${noTrail}`);
    if (opts.ids.length > 0) {
      const found = new Set(rows.map((r) => r.id));
      const missing = opts.ids.filter((id) => !found.has(id));
      console.log(`Requested IDs: ${opts.ids.length} | found ${found.size} | MISSING: ${missing.length ? missing.join(',') : 'none'}`);
    }
    console.log(`Written: ${outPath}`);
  } finally {
    await conn.end();
  }
}

main().catch((err) => {
  console.error('[lookup_codes] FATAL:', err.message);
  process.exitCode = 1;
});
